Added possibility to add default timeout in QueueMessageTemplate / QueueMessageChannel
spring-cloud/spring-cloud-aws pull request #694
Opened 2020-10-07 07:35 UTC by dennis-menge

Refers to gh-646 "Enable long polling in QueueMessagingTemplate #646"

2020-10-18 05:40 UTC, eddumelendez requested changes
@dennis-menge thanks for this contribution! I have added a few suggestions and also wondering if we will need a configuration property `cloud.aws.sqs.default-timeout`

2020-10-18 05:40 UTC, eddumelendez commented on spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageChannel.java
> +		return this.receive(defaultTimeout);
```suggestion
		return this.receive(this.defaultTimeout);
```

2020-10-18 05:40 UTC, eddumelendez commented on spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageChannel.java
> +	public QueueMessageChannel(AmazonSQSAsync amazonSqs, String queueUrl,
I think we can provide an setter instead another constructor

2020-10-18 05:40 UTC, eddumelendez commented on spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageChannel.java
> +		if (timeout == Long.MIN_VALUE) { /* use Queue default timeout */
My suggestion is to do something like this

```java
ReceiveMessageRequest messageRequest = new ReceiveMessageRequest(this.queueUrl)
    .withMaxNumberOfMessages(1)
    .withAttributeNames(ATTRIBUTE_NAMES)
    .withMessageAttributeNames(MESSAGE_ATTRIBUTE_NAMES);
if (timeout != Long.MIN_VALUE) {
    messageRequest.withWaitTimeSeconds(Long.valueOf(timeout).intValue());
}
ReceiveMessageResult receiveMessageResult = this.amazonSqs.receiveMessage(messageRequest);
```

2020-10-22 08:39 UTC, dennis-menge commented
Do you want to introduce a config property or would you prefer to re-use the existing `cloud.aws.sqs.listener.wait-timeout` property?

2022-01-04 16:57 UTC, closed without merging