Enable endpoint customization for each integration
spring-cloud/spring-cloud-aws pull request #715
Opened 2020-11-04 23:36 UTC by maciejwalkowiak

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Adds the ability to specify custom endpoint on service integration properties making it very easy to configure Spring Cloud AWS with Localstack without a need to overwrite a client bean.

## :bulb: Motivation and Context

#570 

## :green_heart: How did you test it?

Unit & Integration tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

2020-11-04 23:36 UTC, maciejwalkowiak commented
Docs will be updated soon.

2020-11-05 14:50 UTC, eddumelendez requested changes
nice feature!

2020-11-05 14:50 UTC, eddumelendez commented on spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/jdbc/AmazonRdsDatabaseAutoConfiguration.java
> +							properties.getEndpoint() != null ? properties.getEndpoint().toString() : null)
can we move this to `String endpoint = properties.getEndpoint() != null ? properties.getEndpoint().toString() : null;` and then use endpoint here?

2020-11-05 14:50 UTC, eddumelendez commented on spring-cloud-aws-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +	  "defaultValue": null,
can be removed

2020-11-05 14:50 UTC, eddumelendez commented on spring-cloud-aws-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +	  "defaultValue": null,
can be removed

2020-11-05 14:50 UTC, eddumelendez commented on spring-cloud-aws-core/src/main/java/org/springframework/cloud/aws/core/config/AwsClientProperties.java
> +public abstract class AwsClientProperties {
I like this but I think we could create a PR just introducing this change and later a new PR introducing the endpoint property.

2020-11-10 21:17 UTC, maciejwalkowiak commented
@eddumelendez I added short docs section. I did not get into details on how to set up with Localstack. Perhaps later.

2020-11-12 11:27 UTC, merged