Add Secrets Manager sample.
spring-cloud/spring-cloud-aws pull request #744
Opened 2020-12-08 13:36 UTC by maciejwalkowiak

Adds Secrets Manager sample and also serves and example on how other sample projects should look like. 

This is a subject to discussion, so your ideas and opinions are welcome.

2020-12-08 17:58 UTC, eddumelendez requested changes

2020-12-08 17:58 UTC, eddumelendez commented on samples/secrets-manager/infrastructure/.gitignore
> +*.js
can we move this file to the .gitignore file in the root folder? Otherwise, we will end up haiving many .gitignore files

2020-12-08 17:58 UTC, eddumelendez commented on samples/secrets-manager/infrastructure/.npmignore
> +*.ts
can we move this file to the root folder? Otherwise, we will end up haiving many .npmignore files

2020-12-08 18:51 UTC, MatejNedic commented on samples/secrets-manager/readme.md
> +This sample application shows how to retrieve a secret from AWS Secrets Manager using Spring Cloud AWS and Spring Boot [Config Import](https://docs.spring.io/spring-boot/docs/2.4.0/reference/html/spr
Should we provide link to https://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_integrating_your_spring_cloud_application_with_the_aws_secrets_manager as well?

2021-01-22 21:21 UTC, maciejwalkowiak commented
Replaced by https://github.com/awspring/spring-cloud-aws/pull/27

2021-01-22 21:21 UTC, closed without merging